topic_prefix: pi
name: fan
mqtt_server_ip: localhost
mqtt_server_port: 1883
mqtt_server_user: mqtt
mqtt_server_password: 123abc

update_freq: 300 # minutes

weather_temp_topic: weather/current
mqtt_set_device_state_topic: zigbee2mqtt/fan
mqtt_set_device_highspeed_state_topic: zigbee2mqtt/fan/highspeed

sensors:
  - zigbee2mqtt/office/temp_sensor