version: '3.6'
services:
  mqttheat:
    build: 
      context: .
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config.yml:/config.yml
    healthcheck:
      test: find . -name healthcheck -mmin -5 -type f -print | grep .
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 1s
#    environment:
#      - LOGLEVEL=DEBUG